# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='blogs',
            field=models.ManyToManyField(to='blog.Blog', verbose_name='Блоги'),
        ),
    ]
